### ISSUE TITLE
Page stage > Some attributes are not load from repository

### ISSUE THREAD

**Issue by eltortuganegra** [Lospitao/myphpisland#152]
When I update the title of a stage it is updated at the database but If I reload the page then all data disappear.

**Comment by Lospitao** [comment]
This functionality is managed by holwer library. Please, execute 
<script type='text/javascript' src='https://cdnjs.cloudflare.com/ajax/libs/howler/2.2.1/howler.js'></script>
cdn link on line 11 of templates/stages/index.html.twig
