### ISSUE TITLE
When users login with bad credentials then an error with a red background should be shown

### ISSUE THREAD

**Issue by eltortuganegra** [Lospitao/myphpisland#186]
Currently, the text of this message:
"Invalid credentials"

![image](https://user-images.githubusercontent.com/5977740/120965248-e9512b80-c764-11eb-8976-6f3582debcfb.png)

1.- The text should be in spanish.
2.- Show like an alert.

**Comment by Lospitao** [comment]
![Screenshot from 2021-06-07 11-21-38](https://user-images.githubusercontent.com/39942410/120992619-13194b00-c783-11eb-9b0d-432bffae0046.png)
